// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GateCore","status":true,"description":"Owns the plugin gate switch.","parameters":{"GateSwitch":"3"}},
{"name":"DependentPlugin","status":true,"description":"Depends on a missing base and is ordered wrong.","parameters":{}},
{"name":"LatePlugin","status":true,"description":"Loads after DependentPlugin (order violation source).","parameters":{}},
{"name":"DisabledPlugin","status":false,"description":"Disabled; must be ignored.","parameters":{}}
];
